-- Migration V8: cria todas as tabelas das entidades do domínio
-- idempotente: usa CREATE TABLE IF NOT EXISTS e índices IF NOT EXISTS

-- Tabela: terrain
CREATE TABLE IF NOT EXISTS terrain (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    size DOUBLE PRECISION,
    location VARCHAR(255),
    lease_value DOUBLE PRECISION
);

-- Tabela: fruit
CREATE TABLE IF NOT EXISTS fruit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_fruit_name ON fruit (name);

-- Tabela: lessor
CREATE TABLE IF NOT EXISTS lessor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Tabela: tb_user
CREATE TABLE IF NOT EXISTS tb_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    CONSTRAINT chk_tb_user_role CHECK (role IN ('ADMIN','USER'))
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_tb_user_email ON tb_user (email);

-- Tabela: harvest
CREATE TABLE IF NOT EXISTS harvest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    box INTEGER NOT NULL,
    terrain_id BIGINT,
    fruit_id BIGINT,
    CONSTRAINT fk_harvest_terrain FOREIGN KEY (terrain_id) REFERENCES terrain (id) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_harvest_fruit FOREIGN KEY (fruit_id) REFERENCES fruit (id) ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_harvest_date ON harvest (date);
CREATE INDEX IF NOT EXISTS idx_harvest_terrain ON harvest (terrain_id);
CREATE INDEX IF NOT EXISTS idx_harvest_fruit ON harvest (fruit_id);

