CREATE TABLE harvest (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE,
    box INTEGER NOT NULL,
    terrain_id BIGINT,
    fruit_id BIGINT,
    CONSTRAINT fk_harvest_terrain FOREIGN KEY (terrain_id) REFERENCES terrain (id),
    CONSTRAINT fk_harvest_fruit FOREIGN KEY (fruit_id) REFERENCES fruit (id)
);