CREATE TABLE sale (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    boxes_sold INTEGER NOT NULL,
    fruit_id BIGINT NOT NULL,
    unit_value INTEGER NOT NULL,
    total_value INTEGER NOT NULL,
    date DATE NOT NULL,
    paid boolean,
    CONSTRAINT fk_sale_fruit FOREIGN KEY (fruit_id) REFERENCES fruit(id)
);

