spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/citricultura
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    jwt:
      secret: 12akd12131o
      expiration-hours: 3600000
    port: 8080
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

